---
title: "Statistics and R for the Life Sciences"
author: "Miao Yu"
date: "2015-01-21"
output: html_document
---

## R BASICS

```{r}
download.file("https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/msleep_ggplot2.csv", 
              destfile = "data/test.csv", method = "curl")
dat = read.csv("data/femaleMiceWeights.csv")


class(tab)
head(tab)
dim(tab)
plot(tab$brainwt, tab$sleep_total)
plot(tab$brainwt, tab$sleep_total, log="x")
summary(tab$sleep_total)

tab[ c(1,2), ]
tab[ tab$sleep_total > 18, ]
tab$sleep_total[ c(1,2) ]

mean(tab[ tab$sleep_total > 18,'sleep_total' ])

which(tab$sleep_total > 18)
tab$sleep_total[ which(tab$sleep_total > 18)[1] ]

which(tab$sleep_total > 18&tab$sleep_rem < 3)[1]

sort(tab$sleep_total)
order(tab$sleep_total)
tab$sleep_total[ order(tab$sleep_total) ]
rank(c(1,2,2,3))
rank(tab$sleep_total) 

match(c("Cow","Owl monkey","Cheetah"), tab$name)
idx = match(c("Cow","Owl monkey","Cheetah"), tab$name)
tab[idx,]

match("Cotton rat", tab$name)

vec = c("red","blue","red","green","green","yellow","orange")
fac = factor(vec)
fac
levels(fac)
fac2 = factor(vec, levels=c("blue","green","yellow","orange","red"))
fac2
levels(fac2)

table(tab$order)

s = split(tab$sleep_total, tab$order)
s
s[[17]]
s[["Rodentia"]]

mean(s[["Rodentia"]])

lapply(s, mean)
sapply(s, mean)
tapply(tab$sleep_total, tab$order, mean)

tapply(tab$sleep_total, tab$order, sd)
```

## Probability Distributions

```{r}
download.file("https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/femaleMiceWeights.csv", 
    destfile = "data/femaleMiceWeights.csv", method = "curl")
dat = read.csv("data/femaleMiceWeights.csv")
mean(dat[13:24,2]) - mean(dat[1:12,2])
s = split(dat[,2], dat[,1])
stripchart(s, vertical=TRUE, col=1:2)
abline(h=sapply(s, mean), col=1:2)

sum(dat[13:24,2]>sapply(s, mean)[1])

sum(dat[1:12,2]>sapply(s, mean)[2])

highfat = s[["hf"]]

sample(highfat, 6)
sample(highfat, 6, replace=TRUE)

sum(highfat > 30)/length(highfat)

download.file("https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/femaleControlsPopulation.csv", 
    destfile = "data/femaleControlsPopulation.csv", method = "curl")

population = read.csv("data/femaleControlsPopulation.csv")
population = population[,1]

mean(population)

sample(population, 12)
mean(sample(population, 12))

sampleMean = replicate(10000, mean(sample(population, 12)))
head(sampleMean)
plot(sampleMean)
null = replicate(10000, mean(sample(population, 12)) - mean(sample(population, 12)))
head(null)
plot(null)

null = replicate(10000, mean(sample(population, 12)) - mean(sample(population, 12)))
hist(null)
diff = mean(dat[13:24,2]) - mean(dat[1:12,2])
abline(v=diff, col="red")
abline(v=-diff, col="red")

1-mean(null<diff)
(1-mean(null<diff))*2

library(devtools)
# install_github("jennybc/gapminder")

library(gapminder)
data(gapminder)
head(gapminder)

x <- gapminder[gapminder$year == 1952,4]
hist(x)

mean(x<=40)
mean(x <= 60) - mean(x <= 40)

prop = function(q) {
  mean(x <= q)
}
prop(40)
qs = seq(from=min(x), to=max(x), length=20)
props = sapply(qs, prop)
plot(qs, props)

props = sapply(qs, function(q) mean(x <= q))
plot(ecdf(x))

y <- gapminder[gapminder$year == 1952,5]
logy <- log10(y)
sd(logy)
hist(logy)
qqnorm(logy)
z <- (logy-mean(logy))/sd(logy)
qqnorm(z)
abline(0,1)
tail(sort(z),1)
F = function(q) pnorm(q, mean=mean(logy), sd=sd(logy))
n = length(logy)

(F(7)-F(6))*n
sum(logy > 6 & logy <= 7)
sort(logy)[1]
n = length(logy)
ps = ((1:n) - 0.5)/n
qnorm(ps)
plot(qnorm(ps), sort(logy))
```

## Infrence

```{r}
download.file("https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/babies.txt", 
    destfile = "data/babies.txt", method = "curl")
babies = read.table("data/babies.txt", header=TRUE)

bwt.nonsmoke = babies$bwt[babies$smoke==0]
bwt.smoke = babies$bwt[babies$smoke==1]

mean(bwt.nonsmoke)-mean(bwt.smoke)
sd(bwt.nonsmoke)
sd(bwt.smoke)

t.test(bwt.nonsmoke[1:30], bwt.smoke[1:30])$statistic

df <- replicate(1000,t.test(sample(bwt.nonsmoke,30), sample(bwt.smoke,30))$conf.int)
mean(df[1,]-df[2,])
popdiff = mean(bwt.nonsmoke) - mean(bwt.smoke)
mean(df[1,]<popdiff & df[2,]>popdiff)

df <- replicate(1000,t.test(sample(bwt.nonsmoke,15), sample(bwt.smoke,15))$p.value<0.1)
mean(df)

df <- replicate(1000,t.test(sample(bwt.nonsmoke,15), sample(bwt.smoke,15))$p.value<0.05)
mean(df)

df <- replicate(1000,t.test(sample(bwt.nonsmoke,15), sample(bwt.smoke,15))$p.value<0.01)
mean(df)

download.file("https://courses.edx.org/c4x/HarvardX/PH525.1x/asset/assoctest.csv", 
    destfile = "data/assoctest.csv", method = "curl")
d = read.csv("data/assoctest.csv")

dt <- table(d) 
chisq.test(dt) 
fisher.test(dt)

vars = replicate(1000, var(sample(bwt.nonsmoke,10)))
mean(vars>var(bwt.nonsmoke)*1.5)

vars = replicate(1000, var(sample(bwt.nonsmoke,50)))
mean(vars>var(bwt.nonsmoke)*1.5)

sample.size = 2:400
var.estimate = sapply(sample.size, function(n) var(sample(bwt.nonsmoke, n)))
plot(sample.size, var.estimate)
abline(h=var(bwt.nonsmoke), col="blue")

set.seed(0)
N <- 50
smokers <- sample(babies$bwt[babies$smoke==1], N)
nonsmokers <- sample(babies$bwt[babies$smoke==0], N)

obs <- mean(smokers) - mean(nonsmokers)

avgdiff <- replicate(1000, {
    all <- sample(c(smokers,nonsmokers))
    smokersstar <- all[1:N]
    nonsmokersstar <- all[(N+1):(2*N)]
    return(mean(smokersstar) - mean(nonsmokersstar))
})

mean(abs(avgdiff) > abs(obs))

obsmed <- median(smokers) - median(nonsmokers)
meddiff <- replicate(1000, {
    all <- sample(c(smokers,nonsmokers))
    smokersstar <- all[1:N]
    nonsmokersstar <- all[(N+1):(2*N)]
    return(median(smokersstar) - median(nonsmokersstar))
})
mean(abs(meddiff) > abs(obsmed))

```

## Exploratory Data Analysis

```{r}
download.file("http://courses.edx.org/c4x/HarvardX/PH525.1x/asset/skew.RData", 
    destfile = "data/skew.RData",method='wget')
load("data/skew.RData")
dim(dat)

par(mfrow = c(3,3))

for (i in 1:9) {
  qqnorm(dat[,i])
}

for (i in 1:9) {
  hist(dat[,i])
}

par(mfrow=c(1,1))

head(InsectSprays)
boxplot(split(InsectSprays$count, InsectSprays$spray))
boxplot(InsectSprays$count ~ InsectSprays$spray)

# install.packages('UsingR')
library(UsingR)
data(father.son)
plot(father.son$fheight, father.son$sheight)
cor(father.son$fheight, father.son$sheight)
identify(father.son$fheight, father.son$sheight)

x = father.son$fheight
y = father.son$sheight
n = nrow(father.son)

plot(scale(x), scale(y))
abline(h=0, v=0)

mean(scale(x)*scale(y))
sum(scale(x) * scale(y)) / (n - 1)

data(nym.2002)
head(nym.2002)
hist(nym.2002$time)
plot(nym.2002$age~nym.2002$time)
plot(nym.2002$time~nym.2002$place)
qqnorm(nym.2002$time)
barplot(tail(sort(table(nym.2002$home)),10))
plot(nym.2002$time~nym.2002$gender)

time = sort(nym.2002$time)
min(time)/median(time)
max(time)/median(time)

plot(time/median(time), ylim=c(1/4,4))
abline(h=c(1/2,1,2))

plot(log2(time/median(time)),ylim=c(-2,2))
abline(h=-1:1)
```

## dplyr

```{r}
library(dplyr)
download.file("https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/msleep_ggplot2.csv", 
    destfile = "data/msleep_ggplot2.csv", method = "curl")
msleep <- read.csv('data/msleep_ggplot2.csv')
head(msleep)

msleep %>%
        mutate(rem_proportion = sleep_rem / sleep_total) %>%
        group_by(order) %>%
        summarise(avg_sleep = median(rem_proportion)) %>%
        arrange(avg_sleep) %>%
        head()
```

## Robust

```{r}
data(ChickWeight)
plot(ChickWeight$Time, ChickWeight$weight, col=ChickWeight$Diet)
head(ChickWeight)
chick = reshape(ChickWeight,idvar=c("Chick","Diet"),timevar="Time",direction="wide")
head(chick)
chick = na.omit(chick)

mean(c(chick$weight.4,3000))/mean(chick$weight.4)
median(c(chick$weight.4,3000))/median(chick$weight.4)
sd(c(chick$weight.4,3000))/sd(chick$weight.4)
mad(c(chick$weight.4,3000))/mad(chick$weight.4)

plot(chick$weight.4~chick$weight.21)

cor(c(chick$weight.4,3000),c(chick$weight.21,3000))/cor(chick$weight.4,chick$weight.21)
cor(c(chick$weight.4,3000),c(chick$weight.21,3000), method = 'spearman')/cor(chick$weight.4,chick$weight.21,method = 'spearman')

stripchart(chick$weight.4 ~ chick$Diet, method="jitter", vertical=TRUE)

t.test(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4])

wilcox.test(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4])

t.test(c(200,chick$weight.4[chick$Diet == 1]),chick$weight.4[chick$Diet == 4])

wilcox.test(c(200,chick$weight.4[chick$Diet == 1]),chick$weight.4[chick$Diet == 4])

par(mfrow=c(1,3))

boxplot(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4])

boxplot(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4]+10)

boxplot(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4]+100)

t.test(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4]+10)$statistic - t.test(chick$weight.4[chick$Diet == 1],chick$weight.4[chick$Diet == 4]+100)$statistic

wilcox.test(c(1,2,3),c(4,5,6))
wilcox.test(c(1,2,3),c(400,500,600))
```

