---
title: "Matrix Algebra and Linear Models"
author: "Miao Yu"
date: "2015-02-17"
output: html_document
---

## Introduction

```{r}
library(UsingR)
?father.son
mean(father.son$sheight)
temp <- father.son[round(father.son$fheight)==71,]
mean(temp[,2])

X = matrix(1:1000,100,10)
X[25,3]

t <- 1:10
x <- cbind(t,2*t,3*t,4*t,5*t)
sum(x[7,])

matrix(1:60,20,3)
matrix(1:60,20,3,byrow=TRUE)
x=11:20;rbind(x,2*x,3*x)
x=1:40;matrix(3*x,20,2)

x <- matrix(c(3,2,1,5,4,2,-1,0,-5,2,5,0,1,-1,-5,1),4,4)
y <- c(10,5,7,4)
solve(x,y)

a <- matrix(1:12, nrow=4)
b <- matrix(1:15, nrow=3)
a%*%b

X <- matrix(c(1,1,1,1,0,0,1,1),nrow=4)
rownames(X) <- c("a","a","b","b")
beta <- c(5, 2)
X%*%beta

X <- matrix(c(1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,1,1),nrow=6)
rownames(X) <- c("a","a","b","b","c","c")
beta <- c(10,3,-3)
X%*%beta

```

## Linear Models

```{r}
# The standard error of an estimate is the standard deviation of the sampling distribution of an estimate. 
g = 9.8 ## meters per second
h0 = 56.67
v0 = 0
n = 25
tt = seq(0,3.4,len=n) ##time in secs, t is a base function
y = h0 + v0 *tt - 0.5* g*tt^2 + rnorm(n,sd=1)
X = cbind(1,tt,tt^2)
A = solve(crossprod(X))%*%t(X)
-2 * (A %*% y) [3] 
temp <- replicate(100000,-2 * (A %*% (h0 + v0 *tt - 0.5* g*tt^2 + rnorm(n,sd=1))) [3] ) 
sd(temp)/sqrt(100000)

library(UsingR)
x = father.son$fheight
y = father.son$sheight
n = length(y)

N = 50
index = sample(n,N)
sampledat = father.son[index,]
x = sampledat$fheight
y = sampledat$sheight
betahat = lm(y~x)$coef

betahats <- replicate(10000,{
        index = sample(n,N)
        sampledat = father.son[index,]
        x = sampledat$fheight
        y = sampledat$sheight
        betahat = lm(y~x)$coef
        return(betahat[2])
})
sd(betahats)
mean((x - mean(x))*(y-mean(y)))

y = h0 + v0*tt - 0.5*g*tt^2 + rnorm(n,sd=1)
var(y)
fit = lm(y ~ x)
sigma2 = sum((y-fit$fitted.values)^2) / 48

X = cbind(rep(1,N), x)
sqrt(sigma2*diag(solve(t(X)%*%X)))
summary(fit)

nx = 5
ny = 7
X = cbind(rep(1,nx + ny),rep(c(0,1),c(nx, ny)))
t(X)%*%X

species <- factor(c("A","A","B","B"))
condition <- factor(c("control","treated","control","treated"))
model.matrix(~ species + condition)

library(contrast)
y = rnorm(4)
fit = lm(y ~ species + condition)
contrast(fit, list(species="B",condition="control"), list(species="A",condition="treated"))$X

spider <- read.csv('data/spider_wolff_gorb_2013.csv',skip = 1)
fitTL <- lm(friction ~ type + leg, data=spider)
contrast(fitTL,list(leg="L4",type="pull"),list(leg="L2",type="pull"))

X <- model.matrix(~ type + leg, data=spider)
(Sigma <- sum(fitTL$residuals^2)/(nrow(X) - ncol(X)) * solve(t(X) %*% X))
Sigma[3,5]
C <- matrix(c(0,0,-1,0,1),1,5)
sqrt(C %*% Sigma %*% t(C))
spider$log2friction <- log2(spider$friction)
boxplot(log2friction ~ type*leg, data=spider)

fitX <- lm(log2friction ~ type + leg + type:leg, data=spider)
summary(fitX)
anova(fitX)

fitX <- lm(log2friction ~ type + leg + type:leg-1, data=spider)
summary(fitX)
contrast(fitX, list(type="pull",leg="L2"), list(type="pull",leg="L1"))
contrast(fitX, list(type="push",leg="L2"), list(type="push",leg="L1"))

N <- 40
p <- 4
group <- factor(rep(1:p,each=N/p))
X <- model.matrix(~ group)

Y <- rnorm(N,mean=42,7)
mu0 <- mean(Y)
initial.ss <- sum((Y - mu0)^2)
s <- split(Y, group)
after.group.ss <- sum(sapply(s, function(x) sum((x - mean(x))^2)))
(group.ss <- initial.ss - after.group.ss)
group.ms <- group.ss / (p - 1)
after.group.ms <- after.group.ss / (N - p)
f.value <- group.ms / after.group.ms

y <- replicate(1000,{
        Y <- rnorm(N,mean=42,7)
        mu0 <- mean(Y)
        initial.ss <- sum((Y - mu0)^2)
        s <- split(Y, group)
        after.group.ss <- sum(sapply(s, function(x) sum((x - mean(x))^2)))
        group.ss <- initial.ss - after.group.ss
        group.ms <- group.ss / (p - 1)
        after.group.ms <- after.group.ss / (N - p)
        f.value <- group.ms / after.group.ms
        return(f.value)
})

hist(y, col="grey", border="white", breaks=50, freq=FALSE)
xs <- seq(from=0,to=6,length=100)
lines(xs, df(xs, df1 = p - 1, df2 = N - p), col="red")
```

## Collinearity

```{r}
sex <- factor(rep(c("female","male"),each=4))
trt <- factor(c("A","A","B","B","C","C","D","D"))
X <- model.matrix( ~ sex + trt)
qr(X)$rank
Y <- 1:8
makeYstar <- function(a,b) Y - X[,2] * a - X[,5] * b
fitTheRest <- function(a,b) {
  Ystar <- makeYstar(a,b)
  Xrest <- X[,-c(2,5)]
  betarest <- solve(t(Xrest) %*% Xrest) %*% t(Xrest) %*% Ystar
  residuals <- Ystar - Xrest %*% betarest
  sum(residuals^2)
}
fitTheRest(1,2)
outer(1:3,1:3,`*`)
min(outer(-2:8,-2:8,Vectorize(fitTheRest)))

library(rafalib)
imagemat(outer(-2:8,-2:8,Vectorize(fitTheRest)))

fit <- lm(friction ~ type + leg, data=spider)
betahat <- coef(fit)
Y <- matrix(spider$friction, ncol=1)
X <- model.matrix(~ type + leg, data=spider)

QR <- qr(X)
Q <- qr.Q( QR )
Q[1,1]
R <- qr.R( QR )
R[1,1]

t(Q)%*%Y
solve(R)%*%t(Q)%*%Y
```

